name: Build docs for Bills Microservice

on:
  push:
    branches:
      - main
env:
  ENVIRONMENT: dev

jobs:
  manage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "here"
          echo "${{ vars.ENV_CONTEXT_VAR }}"
          echo "${{ vars.TEST_VAR }}"
          echo "${{ vars }}"
