name: Build docs for Bills Microservice

on:
  push:
    branches:
      - main
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  manage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "here"
          echo "${{ secrets.DATABASE_URL }}"
