name: Build docs for Bills Microservice

on:
  push:
    branches:
      - main
# env:
#   ENVIRONMENT: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "here"
          echo "${{ toJSON(secrets) }}"
          echo "${{ toJSON(env) }}"
          echo "${{ toJSON(vars) }}"
