name: Build docs for Bills Microservice

on:
  push:
    branches:
      - main
# env:
#   ENVIRONMENT: dev

jobs:
  manage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "here"
          echo "${{ secrets.TEST_VAR }}"
      - name: Iterate over environment variable names
        run: |
          for var in $(compgen -e); do
            echo "$var"
          done