name: Build docs for Bills Microservice

on:
  push:
    branches:
      - main
# env:
#   ENVIRONMENT: dev

jobs:
  manage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "here"
          for key in "${!env[@]}"
          do
            echo "$key: ${env[$key]}"
          done
